# Generated by Django 5.0 on 2024-01-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.DateTimeField(verbose_name='время рассылки'),
        ),
    ]
