# Generated by Django 5.0 on 2024-02-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0003_alter_newsletter_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter_app.client', verbose_name='адресат рассылки'),
        ),
    ]
