# Generated by Django 5.0 on 2024-02-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0009_alter_massage_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='massage',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter_app.newsletter'),
        ),
    ]
