# Generated by Django 5.0 on 2024-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0012_remove_newsletter_client_client_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(to='newsletter_app.client'),
        ),
    ]
