# Generated by Django 5.0 on 2024-02-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0014_remove_newsletter_client_newsletter_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='client',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(to='newsletter_app.client'),
        ),
    ]
