# Generated by Django 5.0 on 2024-03-20 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0016_remove_newsletter_client_newsletter_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='client',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(to='newsletter_app.client'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter_app.massage'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logs',
            name='data_of_attempt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата последней попытки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='mail_server_response',
            field=models.TextField(blank=True, verbose_name='ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter_app.newsletter', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
